INSERT INTO caregiver (login_id, password, name, phone_number, address, has_car, profile_image_url, created_at, updated_at)
VALUES
    ('caregiver1', 'encrypted_password', '정수민', '010-2234-5678', '서울특별시 은평구 응암동', false, NULL, NOW(), NOW()),
    ('caregiver2', 'encrypted_password', '김태호', '010-3456-9012', '서울특별시 강서구 화곡동', true, NULL, NOW(), NOW()),
    ('caregiver3', 'encrypted_password', '전영숙', '010-7890-4567', '서울특별시 송파구 문정동', true, NULL, NOW(), NOW()),
    ('caregiver4', 'encrypted_password', '박준영', '010-5678-2345', '서울특별시 노원구 상계동', true, NULL, NOW(), NOW()),
    ('caregiver5', 'encrypted_password', '임미경', '010-8901-6789', '서울특별시 관악구 신림동', false, NULL, NOW(), NOW()),
    ('caregiver6', 'encrypted_password', '송민재', '010-4567-8901', '서울특별시 마포구 공덕동', true, NULL, NOW(), NOW()),
    ('caregiver7', 'encrypted_password', '황미란', '010-6789-2345', '서울특별시 성북구 정릉동', false, NULL, NOW(), NOW()),
    ('caregiver8', 'encrypted_password', '이상철', '010-9012-5678', '서울특별시 광진구 자양동', true, NULL, NOW(), NOW()),
    ('caregiver9', 'encrypted_password', '유지영', '010-2345-7890', '서울특별시 중랑구 면목동', true, NULL, NOW(), NOW()),
    ('caregiver10', 'encrypted_password', '강성훈', '010-5678-0123', '서울특별시 구로구 구로동', true, NULL, NOW(), NOW()),
    ('caregiver11', 'encrypted_password', '이진호', '010-1122-3344', '서울특별시 동작구 대방동', false, NULL, NOW(), NOW()),
    ('caregiver12', 'encrypted_password', '김민지', '010-2233-4455', '서울특별시 강북구 미아동', true, NULL, NOW(), NOW()),
    ('caregiver13', 'encrypted_password', '박서현', '010-3344-5566', '서울특별시 서초구 서초동', false, NULL, NOW(), NOW()),
    ('caregiver14', 'encrypted_password', '윤상혁', '010-4455-6677', '서울특별시 동대문구 장안동', true, NULL, NOW(), NOW()),
    ('caregiver15', 'encrypted_password', '정혜원', '010-5566-7788', '서울특별시 종로구 혜화동', false, NULL, NOW(), NOW()),
    ('caregiver16', 'encrypted_password', '김도윤', '010-6677-8899', '서울특별시 금천구 독산동', true, NULL, NOW(), NOW()),
    ('caregiver17', 'encrypted_password', '이수정', '010-7788-9900', '서울특별시 성동구 왕십리동', true, NULL, NOW(), NOW()),
    ('caregiver18', 'encrypted_password', '조민호', '010-8899-0011', '서울특별시 마포구 서교동', false, NULL, NOW(), NOW()),
    ('caregiver19', 'encrypted_password', '최예은', '010-9900-1122', '서울특별시 송파구 가락동', true, NULL, NOW(), NOW()),
    ('caregiver20', 'encrypted_password', '배준석', '010-1010-2233', '서울특별시 강남구 논현동', true, NULL, NOW(), NOW()),
    ('caregiver21', 'encrypted_password', '김성민', '010-1111-3333', '서울특별시 관악구 봉천동', false, NULL, NOW(), NOW()),
    ('caregiver22', 'encrypted_password', '강민정', '010-2222-4444', '서울특별시 성북구 안암동', true, NULL, NOW(), NOW()),
    ('caregiver23', 'encrypted_password', '신동현', '010-3333-5555', '서울특별시 용산구 한남동', false, NULL, NOW(), NOW()),
    ('caregiver24', 'encrypted_password', '문지윤', '010-4444-6666', '서울특별시 동작구 노량진동', true, NULL, NOW(), NOW()),
    ('caregiver25', 'encrypted_password', '오태경', '010-5555-7777', '서울특별시 중구 충무로', true, NULL, NOW(), NOW()),
    ('caregiver26', 'encrypted_password', '정지우', '010-6666-8888', '서울특별시 은평구 불광동', false, NULL, NOW(), NOW()),
    ('caregiver27', 'encrypted_password', '장민호', '010-7777-9999', '서울특별시 도봉구 쌍문동', true, NULL, NOW(), NOW()),
    ('caregiver28', 'encrypted_password', '박하린', '010-8888-0000', '서울특별시 서대문구 연희동', false, NULL, NOW(), NOW()),
    ('caregiver29', 'encrypted_password', '최유진', '010-9999-1111', '서울특별시 강남구 삼성동', true, NULL, NOW(), NOW()),
    ('caregiver30', 'encrypted_password', '조재훈', '010-0000-2222', '서울특별시 영등포구 당산동', true, NULL, NOW(), NOW());

INSERT INTO caregiver_optional (caregiver_id, career, description)
VALUES
    (1, 'THREE_TO_FIVE_YEARS', '거동 불편한 어르신 케어 경험 많습니다. 정성껏 모시겠습니다.'),
    (2, 'MORE_THAN_FIVE_YEARS', '건강 관리 및 정서적 교류에 강점이 있습니다. 편안하고 안정적인 돌봄을 제공합니다.'),
    (3, 'MORE_THAN_FIVE_YEARS', '전문적인 투약 관리 가능합니다. 꼼꼼하고 책임감 있게 모시겠습니다.'),
    (4, 'ONE_TO_THREE_YEARS', '남성 어르신 케어 경험 많습니다. 어르신께서 편히 의지할 수 있도록 최선을 다하겠습니다.'),
    (5, 'THREE_TO_FIVE_YEARS', '치매 어르신 돌봄 전문 / 어르신의 일상을 함께하며 따뜻하게 보살피겠습니다.'),
    (6, 'MORE_THAN_FIVE_YEARS', '와상 어르신 케어 특화 / 체위 변경부터 위생 관리까지 세심하게 신경 씁니다.'),
    (7, 'THREE_TO_FIVE_YEARS', '인지활동 프로그램 진행 경험 많습니다. 밝고 활기찬 분위기로 어르신과 소통하겠습니다.'),
    (8, 'ONE_TO_THREE_YEARS', '운동 및 재활 보조 전문, 물리치료 경력 있습니다. 건강한 생활 습관을 돕겠습니다.'),
    (9, 'THREE_TO_FIVE_YEARS', '당뇨 어르신 식사 관리 및 건강 돌봄 전문. 세심하고 꼼꼼하게 챙겨드립니다.'),
    (10, 'MORE_THAN_FIVE_YEARS', '거동이 불편한 어르신 이동 보조 경험 풍부합니다. 안전하고 편안하게 모시겠습니다.'),
    (11, 'ONE_TO_THREE_YEARS', '가정방문 요양 경력 다수, 어르신의 편안한 일상을 돕겠습니다.'),
    (12, 'THREE_TO_FIVE_YEARS', '근력 강화 운동 지도 가능, 어르신의 신체 건강을 위해 함께하겠습니다.'),
    (13, 'MORE_THAN_FIVE_YEARS', '장애인 및 노인 돌봄 경력 다수, 신뢰할 수 있는 케어를 제공합니다.'),
    (14, 'ONE_TO_THREE_YEARS', '기초 재활훈련 가능, 어르신의 재활을 돕겠습니다.'),
    (15, 'THREE_TO_FIVE_YEARS', '치매 전문 교육 이수, 어르신과의 원활한 소통을 위해 노력합니다.'),
    (16, 'MORE_THAN_FIVE_YEARS', '응급 상황 대처 가능, 안전한 돌봄 서비스를 제공합니다.'),
    (17, 'ONE_TO_THREE_YEARS', '어르신 일상 동행 가능, 외출 시 안전을 보장합니다.'),
    (18, 'THREE_TO_FIVE_YEARS', '인지 능력 향상 프로그램 운영 경험 다수, 전문적인 돌봄 가능합니다.'),
    (19, 'MORE_THAN_FIVE_YEARS', '장기 요양 돌봄 경력 7년, 믿을 수 있는 요양 서비스를 제공합니다.'),
    (20, 'ONE_TO_THREE_YEARS', '식사 준비 및 배식 경험 보유, 맞춤형 영양식을 제공합니다.'),
    (21, 'THREE_TO_FIVE_YEARS', '침상 케어 전문, 와상 어르신 케어 경험 다수 보유.'),
    (22, 'MORE_THAN_FIVE_YEARS', '노인 우울증 예방 프로그램 운영 경험 있음.'),
    (23, 'ONE_TO_THREE_YEARS', '소변 및 대변 관리 전문, 기저귀 교체 경험 보유.'),
    (24, 'THREE_TO_FIVE_YEARS', '노인성 질환 이해 및 맞춤형 돌봄 가능.'),
    (25, 'MORE_THAN_FIVE_YEARS', '고혈압, 당뇨 관리 가능한 식단 및 활동 조언 가능.'),
    (26, 'ONE_TO_THREE_YEARS', '간병 도우미 경험, 어르신의 생활을 돕겠습니다.'),
    (27, 'THREE_TO_FIVE_YEARS', '기능 회복 운동 지도 가능, 노약자 체력 강화 도움.'),
    (28, 'MORE_THAN_FIVE_YEARS', '투석 환자 돌봄 가능, 세심한 관리 제공합니다.'),
    (29, 'ONE_TO_THREE_YEARS', '심리 상담 및 정서적 교류 지원 경험 보유.'),
    (30, 'THREE_TO_FIVE_YEARS', '어르신의 독립 생활을 위한 맞춤형 지원 가능.');